### ISSUE TITLE
关于HWCC数据集训练的询问

### ISSUE THREAD

**Issue by xinyiyi99** [back-kh/Palm_Classification#1]
你好！感谢你提供的代码，非常有帮助。我想问一下，这个代码可以用来训练HWCC（手写汉字）数据集吗？是否需要进行一些特定的修改或配置才能兼容？如果有任何建议或指导，非常感谢！

**Comment by back-kh** [comment]
你可以在HWCC数据集上进行训练。此外，还有相关的已有工作，你可以查看这个项目：https://github.com/YusenZhang826/AiM

**Comment by xinyiyi99** [comment]
谢谢
